# Generated by Django 6.0.7 on 2026-08-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
