# Generated by Django 6.0.7 on 2026-08-26 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('education', '0002_reporthistory'),
        ('finance', '0002_alter_wage_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wagerate',
            options={},
        ),
        migrations.AddConstraint(
            model_name='wage',
            constraint=models.UniqueConstraint(fields=('teacher_profile', 'year', 'month'), name='unique_teacher_monthly_wage'),
        ),
        migrations.AddConstraint(
            model_name='wage',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='wage_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wagerate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('semester', 'teacher_profile'), name='unique_active_teacher_semester_wage_rate'),
        ),
        migrations.AddConstraint(
            model_name='wagerate',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wage_rate_amount_positive'),
        ),
    ]
