# Generated by Django 6.0.7 on 2026-08-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='ended_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='started_at',
            field=models.DateField(),
        ),
    ]
