# Generated by Django 6.0.7 on 2026-08-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_reporthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercourse',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.RemoveConstraint(
            model_name='teachercourse',
            name='unique_teacher_course',
        ),
    ]
